# ----- BUILD STAGE -----
FROM debian:bookworm-slim

RUN mkdir -p /usr/share/man/man1

ENV JAVA_TOOL_OPTIONS "-Djava.awt.headless=true"

# Install necessary packages
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -yq install plantuml graphviz git fonts-ipafont fonts-ipaexfont && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /app
COPY docker/plantuml-entrypoint.sh /plantuml-entrypoint.sh
WORKDIR /app

ENTRYPOINT ["/plantuml-entrypoint.sh"]
